No:
	mcs NoBeforeAfter/Main.cs -t:library -r:../../bin/Debug/MyNUnit.exe

BeforeMethod:
	mcs MethodBeforeAfter/Main.cs -t:library -r:../../bin/Debug/MyNUnit.exe

BeforeClass:
	mcs ClassBeforeAfter/Main.cs -t:library -r:../../bin/Debug/MyNUnit.exe

all: No BeforeMethod BeforeClass